// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhkrZIzbNaH2TexdJDoDC6SQsqMcp2YVo',
    appId: '1:215641201728:web:fdb7927dd5fe24ff6e93a5',
    messagingSenderId: '215641201728',
    projectId: 'elearning-app-e957b',
    authDomain: 'elearning-app-e957b.firebaseapp.com',
    storageBucket: 'elearning-app-e957b.firebasestorage.app',
    measurementId: 'G-DW5E29NEM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByQ49sJXuxv1S4P1TGwThjHNZfeaEilZU',
    appId: '1:215641201728:android:5014884ecb3791b86e93a5',
    messagingSenderId: '215641201728',
    projectId: 'elearning-app-e957b',
    storageBucket: 'elearning-app-e957b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:
        'YOUR_IOS_API_KEY', // User should replace based on GoogleService-Info.plist
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: '215641201728',
    projectId: 'elearning-app-e957b',
    storageBucket: 'elearning-app-e957b.firebasestorage.app',
    iosBundleId: 'com.example.elearningApp',
  );
}
